services:
  web:
    image: serv-apjatel:1.0.0
    container_name: serv-apjatel
    restart: always
    command: ["sh", "-c", "python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8005"]
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    ports:
      - "8005:8005"
